config/routes.rb
Rails.application.routes.draw do
  resources :cita_medicas
  resources :doctors
  resources :personas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cita_medica.rb
class CitaMedica < ApplicationRecord
  belongs_to :doctor, :foreign_key =>'doctor_id'
  belongs_to :persona, :foreign_key =>'persona_id'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :citamedica
end

app/models/persona.rb
class Persona < ApplicationRecord
	has_many :citamedica
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cita_medicas_controller.rb
class CitaMedicasController < ApplicationController
  before_action :set_cita_medica, only: [:show, :edit, :update, :destroy]

  # GET /cita_medicas
  # GET /cita_medicas.json
  def index
    @cita_medicas = CitaMedica.all
  end

  # GET /cita_medicas/1
  # GET /cita_medicas/1.json
  def show
  end

  # GET /cita_medicas/new
  def new
    @cita_medica = CitaMedica.new
  end

  # GET /cita_medicas/1/edit
  def edit
  end

  # POST /cita_medicas
  # POST /cita_medicas.json
  def create
    @cita_medica = CitaMedica.new(cita_medica_params)

    respond_to do |format|
      if @cita_medica.save
        format.html { redirect_to @cita_medica, notice: 'Cita medica was successfully created.' }
        format.json { render :show, status: :created, location: @cita_medica }
      else
        format.html { render :new }
        format.json { render json: @cita_medica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cita_medicas/1
  # PATCH/PUT /cita_medicas/1.json
  def update
    respond_to do |format|
      if @cita_medica.update(cita_medica_params)
        format.html { redirect_to @cita_medica, notice: 'Cita medica was successfully updated.' }
        format.json { render :show, status: :ok, location: @cita_medica }
      else
        format.html { render :edit }
        format.json { render json: @cita_medica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cita_medicas/1
  # DELETE /cita_medicas/1.json
  def destroy
    @cita_medica.destroy
    respond_to do |format|
      format.html { redirect_to cita_medicas_url, notice: 'Cita medica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cita_medica
      @cita_medica = CitaMedica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cita_medica_params
      params.require(:cita_medica).permit(:fecha, :doctor_id, :persona_id)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:nombre, :apellido, :edad, :sexo, :telefono)
    end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :apellido, :edad, :sexo, :telefono)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cita_medicas_helper.rb
module CitaMedicasHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/cita_medicas/_form.html.erb
<%= form_with(model: cita_medica, local: true) do |form| %>
  <% if cita_medica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cita_medica.errors.count, "error") %> prohibited this cita_medica from being saved:</h2>

      <ul>
      <% cita_medica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.datetime_select :fecha, id: :cita_medica_fecha %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.select :doctor_id, Doctor.all.collect {|ps| [ps.nombre, ps.id]} %>
  </div>

  <div class="field">
    <%= form.label :persona_id %>
    <%= form.select :persona_id, Persona.all.collect {|ps| [ps.nombre, ps.id]}%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cita_medicas/edit.html.erb
<h1>Editing Cita Medica</h1>

<%= render 'form', cita_medica: @cita_medica %>

<%= link_to 'Show', @cita_medica %> |
<%= link_to 'Back', cita_medicas_path %>

app/views/cita_medicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cita Medicas</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Doctor</th>
      <th>Persona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cita_medicas.each do |cita_medica| %>
      <tr>
        <td><%= cita_medica.fecha %></td>
        <td><%= cita_medica.doctor %></td>
        <td><%= cita_medica.persona %></td>
        <td><%= link_to 'Show', cita_medica %></td>
        <td><%= link_to 'Edit', edit_cita_medica_path(cita_medica) %></td>
        <td><%= link_to 'Destroy', cita_medica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cita Medica', new_cita_medica_path %>

app/views/cita_medicas/new.html.erb
<h1>New Cita Medica</h1>

<%= render 'form', cita_medica: @cita_medica %>

<%= link_to 'Back', cita_medicas_path %>

app/views/cita_medicas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @cita_medica.fecha %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @cita_medica.doctor %>
</p>

<p>
  <strong>Persona:</strong>
  <%= @cita_medica.persona %>
</p>

<%= link_to 'Edit', edit_cita_medica_path(@cita_medica) %> |
<%= link_to 'Back', cita_medicas_path %>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :doctor_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, id: :doctor_apellido %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad, id: :doctor_edad %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :doctor_sexo %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :doctor_telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Sexo</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.nombre %></td>
        <td><%= doctor.apellido %></td>
        <td><%= doctor.edad %></td>
        <td><%= doctor.sexo %></td>
        <td><%= doctor.telefono %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @doctor.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @doctor.apellido %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @doctor.edad %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @doctor.sexo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @doctor.telefono %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personas/_form.html.erb
<%= form_with(model: persona, local: true) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :persona_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, id: :persona_apellido %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad, id: :persona_edad %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :persona_sexo %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :persona_telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Sexo</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.apellido %></td>
        <td><%= persona.edad %></td>
        <td><%= persona.sexo %></td>
        <td><%= persona.telefono %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @persona.apellido %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @persona.edad %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @persona.sexo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @persona.telefono %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>